// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DAL.Migrations
{
    [DbContext(typeof(PhoneBookContext))]
    [Migration("20210310122433_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.PhoneBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("PhoneBookEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Emilia-Romagna, Italy",
                            FirstName = "Seneca",
                            LastName = "Farhana",
                            PhoneNumber = "+35943815315"
                        },
                        new
                        {
                            Id = 2,
                            Address = "	Ingushetia, Russia",
                            FirstName = "Dorofey",
                            LastName = "Juraj",
                            PhoneNumber = "+359 43 985 602"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ireland",
                            FirstName = "Feidhlimidh",
                            LastName = "Benigna",
                            PhoneNumber = "+359 43 061 126"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Icelandic",
                            FirstName = "Katla",
                            LastName = "Gumarich",
                            PhoneNumber = "+359 437 695 17"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Austria",
                            FirstName = "Gregor",
                            LastName = "Eugène",
                            PhoneNumber = "+359 48 083 694"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ceredigion, Wales, United Kingdom",
                            FirstName = "Afon",
                            LastName = "Joetta",
                            PhoneNumber = "+359 437 099 56"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Baden-Württemberg, Germany",
                            FirstName = "Henrik",
                            LastName = "Liudevit",
                            PhoneNumber = "+359 43 049 097"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Gujarat, India",
                            FirstName = "Sachin",
                            LastName = "Esteve",
                            PhoneNumber = "+359 98 568 6606"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Brazil",
                            FirstName = "Filipa",
                            LastName = "Cillian",
                            PhoneNumber = "+359 89 825 1635"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Lombardy, Italy",
                            FirstName = "Crescenzo",
                            LastName = "Stine",
                            PhoneNumber = "+359 43 862 362"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
